/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZBvxXXIB8no
 */
import { Input } from "@/components/ui/input"
import { AvatarImage, Avatar } from "@/components/ui/avatar"

export default function RoomPlayer() {
  return (
    <div className="flex flex-col h-screen bg-white text-gray-900">
      {/* <div className="flex-none p-4">
        <Input className="w-full rounded-md" placeholder="Paste YouTube link here" type="text" />
      </div> */}
      <div className="flex-grow grid grid-cols-3 gap-4 p-4">
        <div className="col-span-2 bg-gray-100 rounded-md overflow-hidden">
          <video
              controls
              autoPlay
              playsInline
              className="w-full rounded-xl mx-auto aspect-video overflow-hidden  object-cover object-center"
              style={{
                aspectRatio: "850/550",
                objectFit: "cover",
              }}
              height="550"
              width="850"
              >
                <source src="/landingpage_shows.mp4" type="video/mp4" />
                Seu navegador não suporta a tag de vídeo.
            </video>
        </div>
        <div className="flex flex-col bg-gray-200 rounded-md">
          <div className="flex-grow overflow-y-auto p-4 space-y-4">
            <div className="flex items-start space-x-2">
              <Avatar>
                <AvatarImage alt="Elliot" src="https://github.com/shadcn.png" />
              </Avatar>
              <div>
                <p className="font-semibold">Elliot</p>
                <p>Sometimes, I wonder if all of this is real or just an illusion. 🤔</p>
              </div>
            </div>
            <div className="flex items-start space-x-2">
              <Avatar>
                <AvatarImage alt="Tyrell" src="/rick.png" />
              </Avatar>
              <div>
                <p className="font-semibold">Tyrell</p>
                <p>Reality, illusion... what matters is what we do with it. So, Elliot, what's the next move?</p>
              </div>
            </div>
          </div>
          <div className="flex-none p-4">
            <Input className="w-full rounded-md shadow-lg" placeholder="Send a message" type="text" />
          </div>
        </div>
      </div>
    </div>
  )
}
